### ISSUE TITLE
False Positive 

### ISSUE THREAD

**Issue by Carriej955** [security-alliance/seal-911#17]
Good day - someone added our site to the blacklist - [prilvnote.com](http://prilvnote.com/) the site itself has nothing to do with cryptocurrencies or web wallets - I ask you to remove us from the blacklist because after reading the rules, not only your resource but also [consensys.io](http://consensys.io/) this is a violation since the site is used for completely different purposes - this action requires consideration by your team!

**Comment by Carriej955** [comment]
Tell me which addresses were affected? I did not receive such funds. Please
note that other imitators may operate on the network - also please note
that adding a site to your service is a violation of the rules described on
the MetaMask website.

**Comment by tayvano** [comment]
Stop lying you ugly butthole.

Start with the 27,575 USDT. They were intended to be sent to TFUQRKkk3rz46QvbQb7cmxdW2KcD37Gvry, as you very well know.

Insetad the funds were sent to TGYwhHDxKmAPJpzznaBedsQoYm66AA1pHY, a wallet we all know **you** control.

Send those back to their rightful owner. Then we can discuss further.

**Comment by Carriej955** [comment]
Can we switch our communication to Telegram?
